version: '3'
services:
  parking_backend:
    image: parking_backend
    ports:
      - "3000:3000"
    depends_on:
      - parking_database
  parking_database:
    image: postgres:14
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyNameIsEminem
      POSTGRES_DB: parking_project
    volumes:
      - postgres:/home/docker-volumes/Severstal/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  parking_frontend:
    image: parking_frontend
    ports:
      - "8080:80"


volumes: 
  postgres:
